// Shared building blocks for the "2 a.m." frames.
// The frames in compositions/frames/ are generated by tools/build-frames.mjs from
// these snippets, so every frame paints the identical night sky and uses the same
// typing engine. Edit here, then run `node tools/build-frames.mjs`.

export const GSAP = '<script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>';

export const FONTS_CSS = `
@font-face { font-family: "Chuk Chat Mono"; src: url("assets/fonts/jetbrains-mono-latin-wght.woff2") format("woff2"); font-weight: 100 800; font-display: block; }
@font-face { font-family: "Chuk Sans"; src: url("assets/fonts/InterVariable.ttf") format("truetype"); font-weight: 100 900; font-display: block; }
@font-face { font-family: "Ubuntu"; src: url("assets/fonts/Ubuntu-wght.ttf") format("truetype"); font-weight: 300 700; font-display: block; }`;

// ---------------------------------------------------------------- seeded random
export function rng(seed) {
  let a = seed >>> 0;
  return function () {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// ---------------------------------------------------------------- night sky
// Copied from chuk.chat usecases.css (.uc-scene--night, .sc-moon). The moon has no halo
// (series rule: no glow). Stars are a fixed seeded list, identical in every frame.
const MOON = { left: 196, top: 96, size: 124, driftPxPerSec: 0.8 };

export function starList() {
  const R = rng(20260927);
  const out = [];
  while (out.length < 64) {
    const x = R() * 1920;
    const y = R() * 1000;
    // keep clear of the moon's path
    const dx = x - (MOON.left + MOON.size / 2);
    const dy = y - (MOON.top + 30 + MOON.size / 2);
    if (Math.hypot(dx, dy) < 120) continue;
    const size = 1.1 + R() * 1.9;
    const base = (0.4 + R() * 0.6) * (y > 760 ? 0.55 : 1);
    const per = 2.6 + R() * 4.2;
    const ph = R() * Math.PI * 2;
    out.push({ x, y, size, base, per, ph });
  }
  return out;
}

export function skyCSS(p) {
  return `
.${p}-sky { position: absolute; inset: 0; overflow: hidden;
  background: radial-gradient(ellipse at 50% 120%, rgba(90, 110, 190, 0.35), transparent 60%),
              linear-gradient(180deg, #0A0F1F 0%, #131A33 55%, #1D2444 100%); }
.${p}-star { position: absolute; border-radius: 50%; background: #ffffff; }
.${p}-moon { position: absolute; left: ${MOON.left}px; top: 0px; width: ${MOON.size}px; height: ${MOON.size}px;
  border-radius: 50%; background: radial-gradient(circle at 36% 34%, #FFF7E4, #EDE1C4 58%, #D2C6A8); }
.${p}-grain { position: absolute; inset: 0; opacity: 0.05; pointer-events: none;
  background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='240' height='240'><filter id='n'><feTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='2' seed='7' stitchTiles='stitch'/><feColorMatrix type='saturate' values='0'/></filter><rect width='240' height='240' filter='url(%23n)'/></svg>");
  background-size: 240px 240px; }`;
}

export function skyHTML(p, dur) {
  const stars = starList()
    .map(
      (s) =>
        `<i class="${p}-star" data-b="${s.base.toFixed(3)}" data-per="${s.per.toFixed(3)}" data-ph="${s.ph.toFixed(3)}" style="left:${s.x.toFixed(1)}px;top:${s.y.toFixed(1)}px;width:${s.size.toFixed(2)}px;height:${s.size.toFixed(2)}px;"></i>`,
    )
    .join("\n        ");
  return `<div class="clip ${p}-sky" id="${p}-sky" data-start="0" data-duration="${dur}" data-track-index="0">
        ${stars}
        <div class="${p}-moon" id="${p}-moon"></div>
        <div class="${p}-grain"></div>
      </div>`;
}

// Pure function of GLOBAL time: star twinkle + the moon sinking.
export function skyJS(p, g0) {
  return `
      var ${p}Stars = Array.prototype.map.call(document.querySelectorAll(".${p}-star"), function (el) {
        return { el: el, b: +el.dataset.b, per: +el.dataset.per, ph: +el.dataset.ph };
      });
      var ${p}Moon = document.getElementById("${p}-moon");
      function ${p}Sky(t) {
        var G = ${g0} + t;
        for (var i = 0; i < ${p}Stars.length; i++) {
          var s = ${p}Stars[i];
          s.el.style.opacity = (s.b * (0.66 + 0.34 * Math.sin((6.28318 * G) / s.per + s.ph))).toFixed(3);
        }
        ${p}Moon.style.transform = "translateY(" + (${MOON.top} + ${MOON.driftPxPerSec} * G).toFixed(2) + "px)";
      }`;
}

// ---------------------------------------------------------------- typing engine
// Deterministic keystroke tapes. Evaluated in the browser (frames) and in node
// (tools/make-audio.mjs, key-press SFX at the exact same times).
export const ENGINE_SRC = String.raw`
function hfRng(seed) {
  var a = seed >>> 0;
  return function () {
    a = (a + 0x6d2b79f5) >>> 0;
    var t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
function hfTape(ops, seed) {
  var R = hfRng(seed);
  var rr = function (a, b) { return a + (b - a) * R(); };
  var t = 0, text = "";
  var ev = [{ t: 0, text: "", k: "idle", c: 0 }];
  var push = function (k, c) { ev.push({ t: Math.round(t * 10000) / 10000, text: text, k: k, c: c }); };
  for (var o = 0; o < ops.length; o++) {
    var op = ops[o];
    if (op.at != null) t = op.at;
    if (op.idle) push("idle", 0);
    if (op.type != null) {
      var sp = op.speed || 1;
      for (var i = 0; i < op.type.length; i++) {
        var ch = op.type[i], prev = text.slice(-1), d;
        if (i === 0 && op.first != null) d = op.first;
        else {
          d = rr(0.05, 0.13);
          if (ch === " ") d = rr(0.07, 0.16);
          else if (prev === " ") d += rr(0.05, 0.2);
          if (R() < 0.07) d += rr(0.12, 0.3);
          d = d / sp;
        }
        t += d; text += ch; push("key", 1);
      }
    }
    if (op.pause) t += op.pause;
    if (op.bs) {
      for (var b = 0; b < op.bs; b++) { t += rr(0.1, 0.16); text = text.slice(0, -1); push("bs", 1); }
    }
    if (op.hold) {
      var delay = op.delay != null ? op.delay : 0.36, rate = op.rate != null ? op.rate : 0.028;
      text = text.slice(0, -1); push("bs", 1);
      t += delay;
      while (text.length) { text = text.slice(0, -1); push("rep", 0); if (text.length) t += rate; }
    }
    if (op.words) {
      var wmin = op.wmin != null ? op.wmin : 0.14, wmax = op.wmax != null ? op.wmax : 0.24;
      while (text.length) { t += rr(wmin, wmax); text = text.replace(/\S*\s*$/, ""); push("bs", 1); }
    }
    if (op.select) { push("sel", 1); t += op.hl != null ? op.hl : 0.45; text = ""; push("del", 1); }
    if (op.send) { push("send", 1); text = ""; push("idle", 0); }
  }
  return ev;
}
function hfAt(ev, t) {
  for (var i = ev.length - 1; i >= 0; i--) if (t >= ev[i].t) return ev[i];
  return ev[0];
}
function hfCaret(ev, t, G) {
  var e = hfAt(ev, t);
  if (e.k === "sel") return false;
  if (e.k !== "idle" && t - e.t < 0.5) return true;
  return Math.floor(G / 0.53) % 2 === 0;
}`;

export function engine() {
  // eslint-disable-next-line no-new-func
  return new Function(ENGINE_SRC + "; return { hfTape: hfTape, hfAt: hfAt, hfCaret: hfCaret };")();
}

// ---------------------------------------------------------------- icons (from chuk.chat app-icons.html)
const S = 'stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"';
export const ICON = {
  menu: `<svg viewBox="0 0 24 24" fill="none"><path d="M4 5L20 5" ${S}/><path d="M4 12L20 12" ${S}/><path d="M4 19L20 19" ${S}/></svg>`,
  pencil: `<svg viewBox="0 0 24 24" fill="none"><path d="M16.4249 4.60509L17.4149 3.6151C18.2351 2.79497 19.5648 2.79497 20.3849 3.6151C21.205 4.43524 21.205 5.76493 20.3849 6.58507L19.3949 7.57506M16.4249 4.60509L9.76558 11.2644C9.25807 11.772 8.89804 12.4078 8.72397 13.1041L8 16L10.8959 15.276C11.5922 15.102 12.228 14.7419 12.7356 14.2344L19.3949 7.57506M16.4249 4.60509L19.3949 7.57506" stroke="currentColor" stroke-linejoin="round" stroke-width="1.5"/><path d="M18.9999 13.5C18.9999 16.7875 18.9999 18.4312 18.092 19.5376C17.9258 19.7401 17.7401 19.9258 17.5375 20.092C16.4312 21 14.7874 21 11.4999 21H11C7.22876 21 5.34316 21 4.17159 19.8284C3.00003 18.6569 3 16.7712 3 13V12.5C3 9.21252 3 7.56879 3.90794 6.46244C4.07417 6.2599 4.2599 6.07417 4.46244 5.90794C5.56879 5 7.21252 5 10.5 5" ${S}/></svg>`,
  image: `<svg viewBox="0 0 24 24" fill="none"><circle cx="7.5" cy="7.5" r="1.5" ${S}/><path d="M2.5 12C2.5 7.52166 2.5 5.28249 3.89124 3.89124C5.28249 2.5 7.52166 2.5 12 2.5C16.4783 2.5 18.7175 2.5 20.1088 3.89124C21.5 5.28249 21.5 7.52166 21.5 12C21.5 16.4783 21.5 18.7175 20.1088 20.1088C18.7175 21.5 16.4783 21.5 12 21.5C7.52166 21.5 5.28249 21.5 3.89124 20.1088C2.5 18.7175 2.5 16.4783 2.5 12Z" stroke="currentColor" stroke-width="1.5"/><path d="M5 21C9.37246 15.775 14.2741 8.88406 21.4975 13.5424" stroke="currentColor" stroke-width="1.5"/></svg>`,
  plus: `<svg viewBox="0 0 24 24" fill="none"><path d="M12 4V20M20 12H4" ${S}/></svg>`,
  flash: `<svg viewBox="0 0 24 24" fill="none"><path d="M5.22576 11.3294L12.224 2.34651C12.7713 1.64397 13.7972 2.08124 13.7972 3.01707V9.96994C13.7972 10.5305 14.1995 10.985 14.6958 10.985H18.0996C18.8729 10.985 19.2851 12.0149 18.7742 12.6706L11.776 21.6535C11.2287 22.356 10.2028 21.9188 10.2028 20.9829V14.0301C10.2028 13.4695 9.80048 13.015 9.3042 13.015H5.90035C5.12711 13.015 4.71494 11.9851 5.22576 11.3294Z" ${S}/></svg>`,
  down: `<svg viewBox="0 0 24 24" fill="none"><path d="M18 9.00005C18 9.00005 13.5811 15 12 15C10.4188 15 6 9 6 9" ${S}/></svg>`,
  mic: `<svg viewBox="0 0 24 24" fill="none"><path d="M12 18V22M12 18H11.5208C8.11765 18 5.28262 15.3914 5 12M12 18H12.4792C15.8824 18 18.7174 15.3914 19 12M12 22H15M12 22H9" ${S}/><path d="M8 6C8 3.79086 9.79086 2 12 2C14.2091 2 16 3.79086 16 6V11C16 13.2091 14.2091 15 12 15C9.79086 15 8 13.2091 8 11V6Z" ${S}/></svg>`,
  send: `<svg viewBox="0 0 24 24" fill="none"><path d="M10.325 5.33455L16.1084 8.24495C19.3643 9.88342 20.9922 10.7027 20.9922 12C20.9922 13.2973 19.3643 14.1166 16.1084 15.7551L10.325 18.6655C6.63532 20.5223 4.79046 21.4507 3.7862 20.7851C3.57349 20.6441 3.38825 20.4651 3.23962 20.2569C2.53788 19.2741 3.3843 17.381 5.07715 13.5948C5.39957 12.8736 5.56078 12.5131 5.58462 12.1319C5.59011 12.044 5.59011 11.956 5.58462 11.8681C5.56078 11.4869 5.39957 11.1264 5.07715 10.4052C3.3843 6.61898 2.53788 4.72586 3.23962 3.74307C3.38825 3.53492 3.57349 3.35593 3.7862 3.21495C4.79046 2.54933 6.63532 3.47774 10.325 5.33455Z" ${S}/><path d="M9.49219 12H13.4922" ${S}/></svg>`,
  right: `<svg viewBox="0 0 24 24" fill="none"><path d="M9.00005 6C9.00005 6 15 10.4189 15 12C15 13.5812 9 18 9 18" ${S}/></svg>`,
  copy: `<svg viewBox="0 0 24 24" fill="none"><path d="M7.5 14.5C7.5 11.2002 7.5 9.55025 8.52513 8.52513C9.55025 7.5 11.2002 7.5 14.5 7.5C17.7998 7.5 19.4497 7.5 20.4749 8.52513C21.5 9.55025 21.5 11.2002 21.5 14.5C21.5 17.7998 21.5 19.4497 20.4749 20.4749C19.4497 21.5 17.7998 21.5 14.5 21.5C11.2002 21.5 9.55025 21.5 8.52513 20.4749C7.5 19.4497 7.5 17.7998 7.5 14.5Z" ${S}/><path d="M7.5 16.5C6.10355 16.5 5.40533 16.5 4.84402 16.3036C3.83866 15.9518 3.0482 15.1613 2.69641 14.156C2.5 13.5947 2.5 12.8964 2.5 11.5V9.5C2.5 6.20017 2.5 4.55025 3.52513 3.52513C4.55025 2.5 6.20017 2.5 9.5 2.5H11.5C12.8964 2.5 13.5947 2.5 14.156 2.69641C15.1613 3.0482 15.9518 3.83866 16.3036 4.84402C16.5 5.40533 16.5 6.10355 16.5 7.5" ${S}/></svg>`,
  refresh: `<svg viewBox="0 0 24 24" fill="none"><path d="M20.0092 2V5.13219C20.0092 5.42605 19.6418 5.55908 19.4537 5.33333C17.6226 3.2875 14.9617 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22C17.5228 22 22 17.5228 22 12" ${S}/></svg>`,
  route: `<svg viewBox="0 0 24 24"><path fill="currentColor" d="M9.78 11.16l-1.42 1.42c-.68-.69-1.34-1.58-1.79-2.94l1.94-.49c.32.89.77 1.5 1.27 2.01zM11 6L7 2 3 6h3.02c.02.81.08 1.54.19 2.17l1.94-.49C8.08 7.2 8.03 6.63 8.02 6H11zm10 0l-4-4-4 4h2.99c-.1 3.68-1.28 4.75-2.54 5.88-.5.44-1.01.92-1.45 1.55-.34-.49-.73-.88-1.13-1.24L9.46 13.6c.93.85 1.54 1.54 1.54 3.4v5h2v-5c0-2.02.71-2.66 1.79-3.63 1.38-1.24 3.08-2.78 3.2-7.37H21z"/></svg>`,
  lock: `<svg viewBox="0 0 24 24"><path fill="currentColor" d="M12 17c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm6-9h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V10c0-1.1-.9-2-2-2zM8.9 6c0-1.71 1.39-3.1 3.1-3.1s3.1 1.39 3.1 3.1v2H8.9V6zM18 20H6V10h12v10z"/></svg>`,
};

// ---------------------------------------------------------------- timing
// Cut = supplied track from 5.05 s. Percussive hits (video time, from `hyperframes beats`
// + RMS transients): 33.44 swell, 35.45, 36.65, 38.65, 39.84, 41.86, 43.06, 45.05, 46.25,
// 48.24, 49.44, 51.44, 52.66, 54.65 (period 3.2 s, pairs 1.2 s apart).
export const TRACK_OFFSET = 5.05;
export const TOTAL = 57.4;
export const FRAMES = [
  { id: "01-hook", start: 0.0, dur: 7.4 },
  { id: "02-questions", start: 7.4, dur: 21.2 },
  { id: "03-who-reads", start: 28.6, dur: 4.8 },
  { id: "04-sent", start: 33.4, dur: 16.04 },
  { id: "05-claim", start: 49.44, dur: 3.22 },
  { id: "06-endcard", start: 52.66, dur: 4.74 },
];
export const startOf = (id) => FRAMES.find((f) => f.id === id).start;
