"""Build index.html for reel 01 (one monolithic composition, 1080x1920).

Run from anywhere: python3 tools/build.py
Scenes live in tools/scenes_*.py, the shared kit in tools/common.py.
Beat map (video seconds, 120 BPM, downbeats on odd seconds from 1.0):
  0.0 tile · 1.0 burst (first kick) · 2.5 Introducing · 3.0 Chuk Chat · 4.75-7.1 kinetic line
  9.0 One private chat. Many worlds. · 11.0 week chat · 17.0 DROP: plan card · 19.5 Done!
  21.0 list 1 · 25.0 invoice chat · 27.8 PDF · 31.0 break: "Now email it to her." · 33.0 email card
  35.5 Done! · 37.0 list 2 · 41.0 Android · 47.5 Done! · 49.0 Connect your apps · 53.0 list 3
  56.3 end card · 57.0 last hit · 59.7 end
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import BASE_CSS, DUR, ENGINE, FINISH, PROJECT  # noqa: E402
import scenes_a  # noqa: E402
import scenes_b  # noqa: E402
import scenes_c  # noqa: E402


def main():
    htmls, csss, jss = [], [scenes_a.LIST_CSS, scenes_a.DONE_CSS, scenes_b.AV_CSS, scenes_b.BUB_CSS, scenes_b.CARD_CSS], []

    h, c, j = scenes_a.burst(); htmls.append(h); csss.append(c); jss.append(j)
    h, c, j = scenes_a.headline(); htmls.append(h); csss.append(c); jss.append(j)
    h, j = scenes_b.week(); htmls.append(h); jss.append(j)
    h, j = scenes_a.done("d1", 19.4, 1.6, scenes_b.avatar("d1", [])); htmls.append(h); jss.append(j)
    h, j = scenes_a.list1(); htmls.append(h); jss.append(j)
    h, j, _th = scenes_b.invoice(); htmls.append(h); jss.append(j)
    h, j = scenes_a.done("d2", 35.4, 1.6, scenes_b.avatar("d2", [])); htmls.append(h); jss.append(j)
    h, j = scenes_a.list2(); htmls.append(h); jss.append(j)
    h, c, j = scenes_c.android(); htmls.append(h); csss.append(c); jss.append(j)
    h, j = scenes_a.done("d3", 47.4, 1.6, scenes_b.avatar("d3", [])); htmls.append(h)
    jss.append(j + "\n" + scenes_b.avatar_js("d3", 47.4, []))
    h, c, j = scenes_c.connect(); htmls.append(h); csss.append(c); jss.append(j)
    h, c, j = scenes_c.ending(); htmls.append(h); csss.append(c); jss.append(j)

    bg_js = """
  // dawn glow: on for the text beats, off for the two chat scenes
  A('#dawn','o',0,0,0,0);
  A('#dawn','o',2.3,0.8,0,1,'o2'); A('#dawn','y',2.3,1.0,320,0,'o3');
  A('#dawn','o',10.8,0.2,1,0,'i2');
  A('#dawn','o',19.4,0.5,0,1,'o2'); A('#dawn','y',19.4,0.7,220,0,'o3');
  A('#dawn','o',24.8,0.2,1,0,'i2');
  A('#dawn','o',35.4,0.5,0,1,'o2'); A('#dawn','y',35.4,0.7,220,0,'o3');
"""
    audio = json.load(open(os.path.join(PROJECT, "audio_meta.json")))
    bgm = audio["bgm"]
    page = f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1080, height=1920" />
    <title>Chuk Chat — Introducing (reel)</title>
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
    <style>
{BASE_CSS}
{"".join(csss)}
    </style>
  </head>
  <body>
    <!-- Generated by tools/build.py. Edit tools/*.py or audio_meta.json, then rerun. -->
    <div id="root" data-composition-id="main" data-start="0" data-duration="{DUR}" data-width="1080" data-height="1920">
      <div id="s-bg" class="clip scene" data-start="0" data-duration="{DUR}" data-track-index="0">
        <div class="bg"></div>
        <div id="dawn" class="dawn"><div class="dawn-a"></div><div class="dawn-b"></div><div class="dawn-c"></div></div>
      </div>
{"".join(htmls)}
      <audio id="bgm" data-timeline-role="music" src="{bgm["path"]}" data-start="0" data-duration="{bgm["duration_s"]}" data-track-index="10" data-volume="{bgm["volume"]}"></audio>
    </div>
    <script>
(function () {{
  var DUR = {DUR};
{ENGINE}
{bg_js}
{"".join(jss)}
{FINISH}
}})();
    </script>
  </body>
</html>
"""
    out = os.path.join(PROJECT, "index.html")
    open(out, "w", encoding="utf-8").write(page)
    print("index.html", len(page) // 1024, "KB")


if __name__ == "__main__":
    main()
