"""Write index.html from script.json and audio_meta.json.

script.json is the one file a later video edits (prompt timing, reply
blocks, cards, camera shots, skies). This tool puts it into the window
host's data-variable-values, mounts the end card and the audio.
Run from anywhere: python3 tools/build_index.py
"""
import html
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
script = json.load(open(os.path.join(ROOT, "script.json")))
audio = json.load(open(os.path.join(ROOT, "audio_meta.json")))

PROMPT = "Announce yourself on YouTube. Keep it short."
LENGTH = float(script["length"])
END_AT, END_LAND = 54.5, 0.5

values = {
    "prompt": PROMPT,
    "chat_title": "Announce yourself",
    "sky": script["skies"][0][1],
    "script": json.dumps(script, ensure_ascii=False, separators=(",", ":")),
}
attr = html.escape(json.dumps(values, ensure_ascii=False, separators=(",", ":")), quote=True)

audio_tags = []
bgm = audio["bgm"]
audio_tags.append(
    f'      <audio id="bgm" data-timeline-role="music" src="{bgm["path"]}" data-start="0" '
    f'data-duration="{bgm["duration_s"]}" data-track-index="10" data-volume="{bgm["volume"]}"></audio>'
)
for i, s in enumerate(audio.get("sfx", [])):
    audio_tags.append(
        f'      <audio id="sfx-{i:02d}" src="{s["file"]}" data-start="{s["at"]}" '
        f'data-duration="{s["duration_s"]}" data-track-index="{20 + i}" data-volume="{s["volume"]}"></audio>'
    )

page = f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1920, height=1080" />
    <title>Chuk Chat — Announce yourself</title>
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
    <style>
      * {{ margin: 0; padding: 0; box-sizing: border-box; }}
      html, body {{ margin: 0; width: 1920px; height: 1080px; overflow: hidden; background: #FDFBF7; }}
      #root {{ position: relative; width: 100%; height: 100%; overflow: hidden; background: #FDFBF7; }}
      #win, #end {{ position: absolute; inset: 0; }}
    </style>
  </head>
  <body>
    <!-- Generated by tools/build_index.py from script.json + audio_meta.json. Edit those, then rerun. -->
    <div id="root" data-composition-id="main" data-start="0" data-duration="{LENGTH:g}" data-width="1920" data-height="1080">
      <div id="win" data-composition-id="chuk-window" data-composition-src="compositions/chuk-window.html"
        data-start="0" data-duration="{LENGTH:g}" data-track-index="1" data-width="1920" data-height="1080"
        data-variable-values="{attr}"></div>
      <div id="end" data-composition-id="end-card" data-composition-src="compositions/end-card.html"
        data-start="{END_AT:g}" data-duration="{LENGTH - END_AT:g}" data-track-index="2" data-width="1920" data-height="1080"
        data-variable-values='{{"ground":"transparent","land_at":{END_LAND:g}}}'></div>
{chr(10).join(audio_tags)}
    </div>
    <script>
      const tl = gsap.timeline({{ paused: true }});
      tl.set({{}}, {{}}, {LENGTH:g});
      window.__timelines["main"] = tl;
    </script>
  </body>
</html>
"""
open(os.path.join(ROOT, "index.html"), "w").write(page)
print("index.html written:", len(page), "bytes")
