"""Build every frame composition and index.html.

Run from anywhere: python3 tools/build.py
Frames live in tools/frames_*.py, the shared kit in tools/kit.py.
index.html mounts every frame at its downbeat and the audio from audio_meta.json.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import frames_a  # noqa: E402

try:
    import frames_b  # noqa: E402
except ImportError:
    frames_b = None
try:
    import frames_c  # noqa: E402
except ImportError:
    frames_c = None

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LENGTH = 64

# (builder, composition id, start, duration)
PLAN = [(frames_a.f00, "f00-hook", 0, 4), (frames_a.f01, "f01-research", 4, 4), (frames_a.f02, "f02-charts", 8, 4),
        (frames_a.f03, "f03-maps", 12, 4), (frames_a.f04, "f04-weather", 16, 4)]
if frames_b:
    PLAN += [(frames_b.f05, "f05-images", 20, 4), (frames_b.f06, "f06-files", 24, 4), (frames_b.f07, "f07-documents", 28, 4),
             (frames_b.f08, "f08-email", 32, 4), (frames_b.f09, "f09-tools", 36, 4)]
if frames_c:
    PLAN += [(frames_c.f10, "f10-workspaces", 40, 4), (frames_c.f11, "f11-models", 44, 4), (frames_c.f12, "f12-android", 48, 4),
             (frames_c.f13, "f13-everywhere", 52, 4), (frames_c.f14, "f14-end", 56, 8)]


def main():
    only = set(sys.argv[1:])
    for fn, fid, *_ in PLAN:
        if not only or fid in only:
            print(fn())
    audio = json.load(open(os.path.join(ROOT, "audio_meta.json")))
    hosts = []
    for _, fid, start, dur in PLAN:
        hosts.append(f'''      <div id="el-{fid}" class="scene" data-composition-id="{fid}" data-composition-src="compositions/frames/{fid}.html"
        data-start="{start}" data-duration="{dur}" data-track-index="1" data-width="1920" data-height="1080"></div>''')
    bgm = audio["bgm"]
    aud = [f'      <audio id="bgm" data-timeline-role="music" src="{bgm["path"]}" data-start="0" '
           f'data-duration="{bgm["duration_s"]}" data-track-index="10" data-volume="{bgm["volume"]}"></audio>']
    for i, s in enumerate(audio.get("sfx", [])):
        aud.append(f'      <audio id="sfx-{i:02d}" src="{s["file"]}" data-start="{s["at"]}" data-duration="{s["duration_s"]}" '
                   f'data-track-index="{20 + i}" data-volume="{s["volume"]}"></audio>')
    nl = "\n"
    page = f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1920, height=1080" />
    <title>Chuk Chat — What it does</title>
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
    <style>
      * {{ margin: 0; padding: 0; box-sizing: border-box; }}
      html, body {{ margin: 0; width: 1920px; height: 1080px; overflow: hidden; background: #FDFBF7; }}
      #root {{ position: relative; width: 100%; height: 100%; overflow: hidden; background: #FDFBF7; }}
      .scene {{ position: absolute; inset: 0; width: 100%; height: 100%; }}
    </style>
  </head>
  <body>
    <!-- Generated by tools/build.py. Edit tools/frames_*.py / tools/kit.py / audio_meta.json, then rerun. -->
    <div id="root" data-composition-id="main" data-start="0" data-duration="{LENGTH}" data-width="1920" data-height="1080">
{nl.join(hosts)}
{nl.join(aud)}
    </div>
    <script>
      const tl = gsap.timeline({{ paused: true }});
      tl.set({{}}, {{}}, {LENGTH});
      window.__timelines["main"] = tl;
    </script>
  </body>
</html>
"""
    open(os.path.join(ROOT, "index.html"), "w").write(page)
    print("index.html:", len(PLAN), "frames")


if __name__ == "__main__":
    main()
