"""CoWork Python agent runtime — the loop, tools, state, and model client (§7)."""

from __future__ import annotations

from .backend import (
    DEFAULT_BASE_URL,
    DEFAULT_MODEL_ID,
    BackendModelClient,
    BackendModelError,
    ResolvedModel,
    SupabaseAuthError,
    SupabaseSession,
    fetch_models_info,
    login,
    resolve_model,
)
from .context import (
    DEFAULT_CONTEXT_LENGTH,
    DEFAULT_RESERVED_OUTPUT,
    SUMMARY_PREFIX,
    SUMMARY_TEMPLATE,
    AuxSummarizer,
    CompressionStats,
    ContextLadder,
    LadderConfig,
    Summarizer,
    build_summary_prompt,
    estimate_message_tokens,
    estimate_messages_tokens,
    estimate_tokens,
    expand_back_references,
    prompt_tokens_from_usage,
    redact_message,
    redact_secrets,
    render_transcript,
)
from .documents import (
    DEFAULT_VISION_MODEL,
    DOCUMENT_MAX_BYTES,
    MARKDOWN_CAP,
    BackendVisionReader,
    VisionError,
    VisionReader,
    anydoc_available,
    build_backend_vision,
    make_read_document_handler,
    register_read_document,
)
from .environment import Environment, LocalEnvironment, ProcessResult
from .files_out import (
    MAX_FILE_BYTES,
    FileSink,
    SentFile,
    make_send_file_handler,
    register_send_file,
    sanitize_name,
)
from .loop import (
    AgentLoop,
    IterationBudget,
    KillSwitch,
    LoopResult,
    StopReason,
)
from .memory import (
    MAX_ENTRY_CHARS,
    MAX_FILE_CHARS,
    MemoryStore,
    MemoryToolError,
    register_memory_tool,
)
from .media import (
    ALLOWED_FLAG_OPTIONS,
    ALLOWED_VALUE_OPTIONS,
    CommandRunner,
    MediaError,
    MediaResult,
    WorkspaceMount,
    make_run_ffmpeg_handler,
    make_run_ffprobe_handler,
    register_media_tools,
    resolve_in_workspace,
    subprocess_runner,
    validate_options,
)
from .model import (
    ModelClient,
    ModelResponse,
    MockModelClient,
    OpenAICompatModelClient,
    ToolCall,
    extract_tool_calls,
    parse_openai_response,
    response_from_content,
)
from .prompt import (
    BASE_INSTRUCTIONS,
    TOOL_PROTOCOL,
    build_system_prompt,
    render_tool_docs,
)
from .registry import ToolRegistry, ToolSpec
from .runtime import build_runtime
from .sandbox_io import (
    CHUNK_BYTES,
    FetchedFile,
    TransferError,
    fetch_bytes,
    stat_file,
)
from .search import (
    register_search_tool,
    sanitize_match,
    search_messages,
    segment_cjk,
)
from .skills import (
    MAX_DESCRIPTION_CHARS,
    Skill,
    SkillError,
    SkillLibrary,
    load_skills,
    parse_skill,
    register_skill_tool,
)
from .state import Message, StateStore
from .think_scrubber import ThinkScrubber, scrub_history, scrub_text
from .tools import register_builtin_tools, register_file_tools, register_run_command
from .web_fetch import (
    FETCH_CAP,
    UrlRejected,
    html_to_markdown,
    is_blocked_address,
    make_web_fetch_handler,
    register_web_fetch,
    validate_url,
)
from .web_search import (
    TokenSession,
    make_web_search_handler,
    register_web_search,
)

__all__ = [
    "ALLOWED_FLAG_OPTIONS",
    "ALLOWED_VALUE_OPTIONS",
    "BASE_INSTRUCTIONS",
    "CHUNK_BYTES",
    "DEFAULT_VISION_MODEL",
    "DOCUMENT_MAX_BYTES",
    "MARKDOWN_CAP",
    "MAX_DESCRIPTION_CHARS",
    "MAX_ENTRY_CHARS",
    "MAX_FILE_BYTES",
    "MAX_FILE_CHARS",
    "SUMMARY_PREFIX",
    "SUMMARY_TEMPLATE",
    "TOOL_PROTOCOL",
    "AgentLoop",
    "AuxSummarizer",
    "BackendModelClient",
    "BackendModelError",
    "BackendVisionReader",
    "CommandRunner",
    "CompressionStats",
    "ContextLadder",
    "DEFAULT_BASE_URL",
    "DEFAULT_CONTEXT_LENGTH",
    "DEFAULT_MODEL_ID",
    "DEFAULT_RESERVED_OUTPUT",
    "Environment",
    "FETCH_CAP",
    "FetchedFile",
    "FileSink",
    "IterationBudget",
    "KillSwitch",
    "LadderConfig",
    "LocalEnvironment",
    "LoopResult",
    "MediaError",
    "MediaResult",
    "MemoryStore",
    "MemoryToolError",
    "Message",
    "ModelClient",
    "ModelResponse",
    "MockModelClient",
    "OpenAICompatModelClient",
    "ProcessResult",
    "ResolvedModel",
    "SentFile",
    "Skill",
    "SkillError",
    "SkillLibrary",
    "StateStore",
    "StopReason",
    "Summarizer",
    "SupabaseAuthError",
    "SupabaseSession",
    "TokenSession",
    "ThinkScrubber",
    "ToolCall",
    "ToolRegistry",
    "ToolSpec",
    "TransferError",
    "UrlRejected",
    "VisionError",
    "VisionReader",
    "WorkspaceMount",
    "anydoc_available",
    "build_backend_vision",
    "build_runtime",
    "build_summary_prompt",
    "build_system_prompt",
    "estimate_message_tokens",
    "estimate_messages_tokens",
    "estimate_tokens",
    "expand_back_references",
    "extract_tool_calls",
    "fetch_bytes",
    "fetch_models_info",
    "html_to_markdown",
    "is_blocked_address",
    "load_skills",
    "login",
    "make_read_document_handler",
    "make_run_ffmpeg_handler",
    "make_run_ffprobe_handler",
    "make_send_file_handler",
    "make_web_fetch_handler",
    "make_web_search_handler",
    "parse_openai_response",
    "parse_skill",
    "prompt_tokens_from_usage",
    "redact_message",
    "redact_secrets",
    "register_builtin_tools",
    "register_file_tools",
    "register_media_tools",
    "register_memory_tool",
    "register_read_document",
    "register_run_command",
    "register_search_tool",
    "register_send_file",
    "register_skill_tool",
    "register_web_fetch",
    "register_web_search",
    "render_tool_docs",
    "render_transcript",
    "resolve_in_workspace",
    "resolve_model",
    "response_from_content",
    "sanitize_match",
    "sanitize_name",
    "search_messages",
    "segment_cjk",
    "stat_file",
    "subprocess_runner",
    "validate_options",
    "validate_url",
    "scrub_history",
    "scrub_text",
]
