import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math';
import 'dart:typed_data';

import 'package:flutter/services.dart' show rootBundle;

/// Reads one app asset. Injected so the server can be tested without a bundle.
typedef VncAssetReader = Future<Uint8List> Function(String assetKey);

Future<Uint8List> _bundleAsset(String assetKey) async {
  final ByteData data = await rootBundle.load(assetKey);
  return data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
}

/// The loopback server that feeds the noVNC viewer page.
///
/// It does two jobs at one port: it serves the viewer page and the vendored
/// noVNC library out of the app bundle, and it carries the RFB byte stream as
/// a WebSocket. noVNC speaks WebSocket, not raw TCP, so the plain loopback
/// `ServerSocket` the old pure-Dart client dialled cannot be reused.
///
/// Hardening. A listening loopback port on a phone is reachable by every other
/// app on that phone, and this one carries the agent's screen in one direction
/// and keystrokes in the other. So:
///
///  * Every path is behind a per-view token of 256 random bits, generated by
///    [Random.secure]. Without it there is no page, no library and no socket —
///    a scan finds a server that answers 404 to everything.
///  * The token is compared in constant time, so a caller cannot walk it out
///    byte by byte off the response timing.
///  * The WebSocket upgrade also checks `Origin`. Only the page this server
///    itself served has the right one, so a WebSocket opened from any other
///    page — a browser tab, another app's WebView — is refused.
///  * Exactly one WebSocket at a time. A second attempt is refused and does
///    not disturb the first, which is the rule the old loopback socket had.
///    The slot reopens once the page's own socket closes, because the page
///    has to be able to reconnect after a drop.
///  * Only two asset roots are reachable, and only files under them, so a
///    path cannot walk out of the viewer into the rest of the bundle.
///
/// The token rides the page URL because the WebSocket handshake has nowhere
/// else to put it. The VNC password does not: it is handed to the page by a
/// JavaScript call after load, so it never lands in a URL, a history entry or
/// a log line.
class VncLocalServer {
  VncLocalServer._(
    this._server,
    this._token,
    this._readAsset,
    this.onStreamRestartNeeded,
  ) {
    _server.listen(
      _handle,
      onError: (Object _) {},
      cancelOnError: false,
    );
  }

  /// The roots a request may name, mapped to their place in the app bundle.
  /// Everything else is a 404, including a path with a `..` segment.
  static const Map<String, String> _roots = <String, String>{
    'vnc': 'assets/vnc',
    'novnc': 'assets/novnc',
  };

  /// A plain file or folder name: letters, digits, dot, dash, underscore.
  static final RegExp _safeSegment = RegExp(r'^[A-Za-z0-9._-]+$');

  static const Map<String, String> _mimeTypes = <String, String>{
    'html': 'text/html; charset=utf-8',
    // Required, not cosmetic: a browser refuses to run an ES module that is
    // not served as JavaScript, and the whole viewer is ES modules.
    'js': 'text/javascript; charset=utf-8',
    'css': 'text/css; charset=utf-8',
    'txt': 'text/plain; charset=utf-8',
  };

  final HttpServer _server;
  final String _token;
  final VncAssetReader _readAsset;

  /// Called when the viewer page loses its socket after bytes had flowed.
  ///
  /// The RFB stream is a tunnel, not a server: the executor holds ONE socat
  /// pipe into the agent's x11vnc, and it stays mid-protocol when the page
  /// goes away. A page that dials back in would resume someone else's
  /// half-read handshake and fail forever. So a lost page is a request to
  /// tear the executor's pipe down and open a fresh one.
  final Future<void> Function()? onStreamRestartNeeded;

  WebSocket? _socket;
  // True while a socket is attached OR an upgrade is in flight, so a racing
  // second upgrade cannot slip in between the check and the handshake.
  bool _socketBusy = false;
  bool _sawBytes = false;
  bool _closed = false;

  /// Bytes the viewer page sent, which are RFB client messages for the agent's
  /// x11vnc.
  final StreamController<Uint8List> _fromPage =
      StreamController<Uint8List>.broadcast();

  /// Server bytes that arrived before the page opened its socket. x11vnc
  /// speaks first, so its greeting can beat the WebView's load.
  final List<Uint8List> _pending = <Uint8List>[];

  /// Binds on the loopback interface at an ephemeral port.
  static Future<VncLocalServer> start({
    VncAssetReader? readAsset,
    Random? random,
    Future<void> Function()? onStreamRestartNeeded,
  }) async {
    final HttpServer server = await HttpServer.bind(
      InternetAddress.loopbackIPv4,
      0,
      shared: false,
    );
    // The listen queue is short on purpose: nothing legitimate opens more than
    // one connection at a time here.
    server.idleTimeout = const Duration(seconds: 30);
    return VncLocalServer._(
      server,
      _mintToken(random ?? Random.secure()),
      readAsset ?? _bundleAsset,
      onStreamRestartNeeded,
    );
  }

  static String _mintToken(Random random) {
    final Uint8List bytes = Uint8List(32);
    for (int i = 0; i < bytes.length; i++) {
      bytes[i] = random.nextInt(256);
    }
    return base64Url.encode(bytes).replaceAll('=', '');
  }

  int get port => _server.port;

  /// The token, for tests. Never logged and never shown.
  String get token => _token;

  /// The page to load in the WebView. The WebSocket URL rides the query, so
  /// the page can hand it straight to noVNC.
  Uri get viewerUrl {
    final String socket = 'ws://127.0.0.1:$port/$_token/rfb';
    return Uri.parse(
      'http://127.0.0.1:$port/$_token/vnc/viewer.html'
      '?ws=${Uri.encodeQueryComponent(socket)}',
    );
  }

  /// The origin the viewer page runs at, and the only one allowed to open the
  /// WebSocket.
  String get _origin => 'http://127.0.0.1:$port';

  /// RFB client messages on their way to the agent's screen.
  Stream<Uint8List> get fromPage => _fromPage.stream;

  /// True once the viewer page has its socket. Until then [send] buffers.
  bool get hasClient => _socket != null;

  /// Push RFB server bytes toward the page, or hold them until it dials in.
  void send(Uint8List bytes) {
    if (_closed) return;
    _sawBytes = true;
    final WebSocket? socket = _socket;
    if (socket == null) {
      _pending.add(bytes);
      return;
    }
    try {
      socket.add(bytes);
    } catch (_) {
      // A dead socket is the page going away, not an app-level failure.
    }
  }

  /// Drop the page's socket and every buffered byte, because the stream behind
  /// it was replaced.
  ///
  /// The executor re-handshakes with the agent's x11vnc by itself. When it
  /// does, the bytes now arriving are a FRESH RFB session that starts at the
  /// version line, and the page is still half way through the old one. Closing
  /// its socket is what makes it start over: noVNC holds its last frame, sees
  /// the drop, and dials back in for a clean handshake.
  ///
  /// Unlike a socket the PAGE lost, this does not ask for another executor
  /// restart — the executor is the one that just restarted.
  void resetStream() {
    final WebSocket? socket = _socket;
    _socket = null;
    _socketBusy = false;
    _sawBytes = false;
    _pending.clear();
    if (socket == null) return;
    try {
      socket.close();
    } catch (_) {}
  }

  Future<void> close() async {
    if (_closed) return;
    _closed = true;
    final WebSocket? socket = _socket;
    _socket = null;
    _pending.clear();
    try {
      await socket?.close();
    } catch (_) {}
    await _fromPage.close();
    await _server.close(force: true);
  }

  // Equal-length, constant-time comparison. A plain `==` on a secret leaks its
  // prefix through the time it takes to fail.
  static bool _tokensMatch(String a, String b) {
    if (a.length != b.length) return false;
    int diff = 0;
    for (int i = 0; i < a.length; i++) {
      diff |= a.codeUnitAt(i) ^ b.codeUnitAt(i);
    }
    return diff == 0;
  }

  Future<void> _handle(HttpRequest request) async {
    try {
      await _route(request);
    } catch (_) {
      try {
        request.response.statusCode = HttpStatus.internalServerError;
        await request.response.close();
      } catch (_) {}
    }
  }

  Future<void> _route(HttpRequest request) async {
    final List<String> segments = request.uri.pathSegments;
    // Every path shape that is not `/<token>/<root>/<file...>` is a 404, and
    // so is a wrong token. One answer for all of them: a scanner learns
    // nothing from the difference between "no such file" and "wrong token".
    if (segments.length < 2 || !_tokensMatch(segments.first, _token)) {
      return _notFound(request);
    }
    if (segments.length == 2 && segments[1] == 'rfb') {
      return _upgrade(request);
    }
    if (segments.length < 3) return _notFound(request);
    final String? root = _roots[segments[1]];
    if (root == null) return _notFound(request);
    final List<String> rest = segments.sublist(2);
    // Every segment must be a plain file or folder name. `pathSegments`
    // percent-DECODES, so `%2F` arrives as a slash inside one segment and a
    // rule that only rejected a bare `..` would let `..%2F..%2Fx` walk out of
    // the viewer. An allow-list of characters closes that for good.
    if (rest.any((String s) => !_safeSegment.hasMatch(s) || s == '.' || s == '..')) {
      return _notFound(request);
    }
    return _serveAsset(request, '$root/${rest.join('/')}');
  }

  Future<void> _serveAsset(HttpRequest request, String assetKey) async {
    if (request.method != 'GET') return _notFound(request);
    final Uint8List body;
    try {
      body = await _readAsset(assetKey);
    } catch (_) {
      return _notFound(request);
    }
    final String extension = assetKey.split('.').last.toLowerCase();
    final HttpResponse response = request.response;
    response.statusCode = HttpStatus.ok;
    response.headers.contentType = ContentType.parse(
      _mimeTypes[extension] ?? 'application/octet-stream',
    );
    // The page is a view of a remote screen and nothing else. It may load its
    // own files and open its own WebSocket; it may not reach the network, and
    // nothing may frame it.
    response.headers.set(
      'Content-Security-Policy',
      "default-src 'none'; script-src 'self'; style-src 'self'; "
      "img-src 'self' data: blob:; connect-src $_origin ws://127.0.0.1:$port; "
      "frame-ancestors 'none'; base-uri 'none'",
    );
    response.headers.set('Cache-Control', 'no-store');
    response.headers.set('X-Content-Type-Options', 'nosniff');
    // The token is in this URL, so it must not travel out with a navigation.
    response.headers.set('Referrer-Policy', 'no-referrer');
    response.add(body);
    await response.close();
  }

  Future<void> _upgrade(HttpRequest request) async {
    if (!WebSocketTransformer.isUpgradeRequest(request)) {
      return _notFound(request);
    }
    // Only the page this server served may open the socket.
    final String? origin = request.headers.value('origin');
    if (origin != _origin) {
      request.response.statusCode = HttpStatus.forbidden;
      await request.response.close();
      return;
    }
    // One socket at a time. A second attempt is refused without touching the
    // first, so a stray local process can neither watch the screen nor inject
    // input by racing the page. The slot reopens when the page's own socket
    // closes, because the page must be able to reconnect after a drop.
    if (_socketBusy || _closed) {
      request.response.statusCode = HttpStatus.conflict;
      await request.response.close();
      return;
    }
    _socketBusy = true;
    final WebSocket socket = await WebSocketTransformer.upgrade(request);
    _socket = socket;
    for (final Uint8List chunk in _pending) {
      try {
        socket.add(chunk);
      } catch (_) {}
    }
    _pending.clear();
    socket.listen(
      (Object? message) {
        if (message is List<int> && !_fromPage.isClosed) {
          _fromPage.add(Uint8List.fromList(message));
        }
        // A text frame is not RFB. Ignore it rather than forward it.
      },
      onError: (Object _) => _dropSocket(socket),
      onDone: () => _dropSocket(socket),
      cancelOnError: true,
    );
  }

  void _dropSocket(WebSocket socket) {
    if (!identical(_socket, socket)) return;
    _socket = null;
    _socketBusy = false;
    // Buffered server bytes belong to the pipe the lost page was reading. A
    // fresh page must not be handed the tail of someone else's handshake.
    _pending.clear();
    if (_closed || !_sawBytes) return;
    _sawBytes = false;
    onStreamRestartNeeded?.call();
  }

  Future<void> _notFound(HttpRequest request) async {
    request.response.statusCode = HttpStatus.notFound;
    await request.response.close();
  }
}
