import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:cryptography/cryptography.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:chuk_chat/services/cowork/cowork_approved_devices.dart';
import 'package:chuk_chat/services/cowork/cowork_device_keys.dart';
import 'package:chuk_chat/services/cowork/cowork_frame.dart';
import 'package:chuk_chat/services/cowork/cowork_frame_codec.dart';

/// Cross-language byte-compatibility proof for the CoWork frame crypto.
///
/// The vector in `test/fixtures/cowork_crypto_vectors.json` is generated by the
/// Python twin (`common/cowork_crypto/tests/gen_vectors.py`) from a fixed
/// Ed25519 seed, a fixed channel key, a fixed nonce and fixed
/// seq/ts/device_id/kv. Ed25519 is deterministic (RFC 8032), so with those
/// same inputs the Dart `CoworkFrameSealer` must reproduce byte-identical
/// header, signed bytes, ciphertext, signature and frame JSON — and open the
/// frame back to the same plaintext. If Dart and Python ever diverge on the
/// wire, this test fails on the exact differing field.
void main() {
  // The vector fixture lives beside the test; flutter test runs with the
  // package root as cwd, so this relative path resolves under `flutter test`.
  final Map<String, dynamic> vectors =
      jsonDecode(
            File('test/fixtures/cowork_crypto_vectors.json').readAsStringSync(),
          )
          as Map<String, dynamic>;
  final Map<String, dynamic> inputs = vectors['inputs'] as Map<String, dynamic>;
  final Map<String, dynamic> expected =
      vectors['expected'] as Map<String, dynamic>;

  final List<int> channelKey = base64Decode(inputs['channel_key_b64'] as String);
  final List<int> ed25519Seed = base64Decode(inputs['ed25519_seed_b64'] as String);
  final List<int> nonceBytes = base64Decode(inputs['nonce_b64'] as String);
  final String deviceId = inputs['device_id'] as String;
  final int keyVersion = inputs['key_version'] as int;
  final int seq = inputs['seq'] as int;
  final int ts = inputs['ts'] as int;
  final String plaintext = inputs['plaintext_utf8'] as String;

  DateTime fixedClock() => DateTime.fromMillisecondsSinceEpoch(ts, isUtc: true);

  group('CoWork crypto cross-language vectors', () {
    late SimpleKeyPair signingKeyPair;
    late SimplePublicKey signingPublicKey;

    setUp(() async {
      signingKeyPair = await CoworkDeviceKeys.fromSeed(ed25519Seed);
      signingPublicKey = await signingKeyPair.extractPublicKey();
    });

    test('device identity derived from the seed matches the fixture', () async {
      // Guards that both sides agree on the Ed25519 public key + fingerprint,
      // so a signature mismatch below can never be blamed on a wrong key.
      expect(
        base64Encode(signingPublicKey.bytes),
        inputs['ed25519_public_b64'],
      );
      expect(
        CoworkDeviceKeys.fingerprint(signingPublicKey),
        inputs['fingerprint'],
      );
    });

    test('Sealer reproduces byte-identical frame bytes', () async {
      final sealer = CoworkFrameSealer.withChannelKey(
        channelKey: channelKey,
        keyVersion: keyVersion,
        deviceId: deviceId,
        signingKeyPair: signingKeyPair,
        nextSeq: seq,
        clock: fixedClock,
        random: _FixedByteRandom(nonceBytes),
      );

      final frame = await sealer.sealText(plaintext);

      // Header (AAD) and signed bytes: the length-prefixed field encoding must
      // match byte for byte across languages.
      expect(base64Encode(frame.headerBytes), expected['header_b64']);
      expect(base64Encode(frame.signedBytes), expected['signed_b64']);

      // AEAD output and the deterministic Ed25519 signature.
      expect(base64Encode(frame.nonce), expected['nonce_b64']);
      expect(base64Encode(frame.ciphertext), expected['ciphertext_b64']);
      expect(base64Encode(frame.sig), expected['sig_b64']);

      // The full JSON frame as it travels the relay, key order included.
      expect(frame.toJsonString(), expected['frame_json']);

      // The sealer advanced its own counter past the sealed seq.
      expect(sealer.nextSeq, seq + 1);
    });

    test('Opener decrypts the fixture frame to the expected plaintext', () async {
      final approved = CoworkApprovedDevices()
        ..approve(deviceId, signingPublicKey);
      final opener = CoworkFrameOpener.withChannelKey(
        channelKey: channelKey,
        keyVersion: keyVersion,
        approvedDevices: approved,
        clock: fixedClock,
      );

      final frame = CoworkFrame.fromJsonString(expected['frame_json'] as String);
      final opened = await opener.openText(frame);

      expect(opened, plaintext);
    });

    test('Sealer output round-trips back through the Opener', () async {
      final sealer = CoworkFrameSealer.withChannelKey(
        channelKey: channelKey,
        keyVersion: keyVersion,
        deviceId: deviceId,
        signingKeyPair: signingKeyPair,
        nextSeq: seq,
        clock: fixedClock,
        random: _FixedByteRandom(nonceBytes),
      );
      final frame = await sealer.sealText(plaintext);

      final approved = CoworkApprovedDevices()
        ..approve(deviceId, signingPublicKey);
      final opener = CoworkFrameOpener.withChannelKey(
        channelKey: channelKey,
        keyVersion: keyVersion,
        approvedDevices: approved,
        clock: fixedClock,
      );

      expect(await opener.openText(frame), plaintext);
    });

    test('withChannelKey rejects a key that is not 32 bytes', () {
      expect(
        () => CoworkFrameSealer.withChannelKey(
          channelKey: List<int>.filled(16, 0),
          keyVersion: keyVersion,
          deviceId: deviceId,
          signingKeyPair: signingKeyPair,
        ),
        throwsArgumentError,
      );
      expect(
        () => CoworkFrameOpener.withChannelKey(
          channelKey: List<int>.filled(16, 0),
          keyVersion: keyVersion,
          approvedDevices: CoworkApprovedDevices(),
        ),
        throwsArgumentError,
      );
    });
  });
}

/// A [Random] that hands out a fixed byte sequence through [nextInt], so the
/// sealer draws the vector's pinned nonce instead of a real random one. Only
/// [nextInt] is used by the codec; the rest is unreachable in this test.
class _FixedByteRandom implements Random {
  _FixedByteRandom(this._bytes);

  final List<int> _bytes;
  int _index = 0;

  @override
  int nextInt(int max) {
    // The codec calls nextInt(256) once per nonce byte, in order.
    final value = _bytes[_index++];
    if (value < 0 || value >= max) {
      throw StateError('fixed byte $value out of range for nextInt($max)');
    }
    return value;
  }

  @override
  bool nextBool() => throw UnimplementedError();

  @override
  double nextDouble() => throw UnimplementedError();
}
