"""What a completion notification says (docs/WIRE_CONTRACT.md, P7).

A notification has one job: tell the reader, in a glance, which of their things
just happened. The reader knows two names — the coworker they talk to and, when
a schedule or a watcher started the run, the automation they set up. They have
never seen the roster name (``ivory-lynx``): it is generated by
``chuk_agents_manager.names.random_name`` and doubles as the workspace directory
name, so it is an implementation detail and must never reach a toast.

This module owns both halves of that:

* the wording (:func:`completion_text`, :func:`approval_text`) — pure, so the
  tests read like the notification;
* the lookup (:func:`resolve_labels`) — the automation's name from the
  ``automations`` table, the coworker's from ``coworker_names``, both
  best-effort: a missing table or a stale id degrades to the generic label, and
  never to the codename.

The text still carries NO answer content, which is the P7 rule that made these
notifications generic in the first place. What changed is only that "generic"
no longer means "meaningless".
"""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass
from pathlib import Path

from .coworker_names import host_agent_id

#: Used when the user never named this coworker in the app. Honest and dull
#: beats a codename the reader cannot place.
DEFAULT_COWORKER = "Your coworker"

#: An automation name is user-typed; a notification line is one line.
MAX_LABEL_LEN = 60


@dataclass(frozen=True)
class RunLabels:
    """The names a reader recognises. Both may be unknown."""

    coworker: str | None = None
    automation: str | None = None

    @property
    def who(self) -> str:
        return _clip(self.coworker) or DEFAULT_COWORKER

    @property
    def headline(self) -> str:
        """The title: the coworker, and the automation when one drove the run.
        Two names, because either alone leaves the reader guessing — whose
        thread is this, and what did I ask for.

        Users name both after the same job ("Wahlradar" watching "Wahlradar LT
        Sachsen-Anhalt 2026"); repeating the word buys the reader nothing, so
        one name that already carries the other stands alone."""
        automation = _clip(self.automation)
        if not automation:
            return self.who
        if self.who.casefold() in automation.casefold():
            return automation
        return f"{self.who}: {automation}"


def completion_text(labels: RunLabels, *, failed: bool = False) -> tuple[str, str]:
    """Title and body for a run that ended. The body says what happened; it
    never asks the user to finish something the host already finished."""
    if failed:
        return (labels.headline, "The run did not finish. Open the app to see what happened.")
    return (labels.headline, "The answer is ready. Open the app to read it.")


def approval_text(labels: RunLabels) -> tuple[str, str]:
    """Title and body for a run that is blocked on a publish approval."""
    return (f"{labels.who} needs your approval", "Open the app to allow or deny the publish.")


def resolve_labels(
    *,
    db_path: str,
    roster_path: str | None = None,
    automation_id: str | None = None,
    session_key: str | None = None,
) -> RunLabels:
    """Read the names out of the host's SQLite files. Best-effort by design:
    this runs on the notification thread, and a locked or missing database must
    cost the reader a name, never the notification."""
    return RunLabels(
        coworker=coworker_name(roster_path or default_roster_path(db_path), session_key=session_key),
        automation=automation_name(db_path, automation_id),
    )


def default_roster_path(db_path: str) -> str:
    """``roster.db`` sits next to the executor state in the host workspace
    (see ``AgentsHost.__init__``); the notifier is handed only the latter."""
    return str(Path(db_path).with_name("roster.db"))


def coworker_name(
    roster_path: str,
    *,
    session_key: str | None = None,
    device_id: str | None = None,
) -> str | None:
    """The name the user gave the coworker whose thread this run belongs to.

    A thread key IS the app's agent id (``agent_roster_source`` gives each
    coworker one thread keyed by the id), which is the key ``coworker_names``
    is written under — so the run's ``session_key`` names the right coworker
    even when the user has several. The host's own coworker
    (``host:<device id>``) is the fallback, and None when nothing is named.
    """
    candidates = [key for key in (session_key, host_agent_id(device_id) if device_id else host_agent_id()) if key]
    for agent_id in candidates:
        row = _query_one(
            roster_path,
            "SELECT name FROM coworker_names WHERE agent_id = ?",
            (agent_id,),
        )
        name = _clean(row[0]) if row else None
        if name:
            return name
    return None


def automation_name(db_path: str, automation_id: str | None) -> str | None:
    """The name of the automation that fired this run, or None when the run
    was not fired by one (or the automation has since been deleted)."""
    if not automation_id:
        return None
    row = _query_one(db_path, "SELECT name FROM automations WHERE id = ?", (str(automation_id),))
    return _clean(row[0]) if row else None


def _query_one(path: str, sql: str, params: tuple) -> tuple | None:
    try:
        conn = sqlite3.connect(f"file:{path}?mode=ro", uri=True, timeout=2.0)
    except sqlite3.Error:
        return None
    try:
        return conn.execute(sql, params).fetchone()
    except sqlite3.Error:  # table not created yet, file locked, database busy
        return None
    finally:
        conn.close()


def _clean(value: object) -> str | None:
    if not isinstance(value, str):
        return None
    return value.strip() or None


def _clip(value: str | None) -> str | None:
    name = _clean(value)
    if name is None:
        return None
    return name if len(name) <= MAX_LABEL_LEN else name[: MAX_LABEL_LEN - 1].rstrip() + "…"
