import 'package:highlight/highlight_core.dart';
import 'package:highlight/languages/dart.dart';
import 'package:highlight/languages/json.dart';
import 'package:highlight/languages/python.dart';
import 'package:highlight/languages/javascript.dart';
import 'package:highlight/languages/typescript.dart';
import 'package:highlight/languages/java.dart';
import 'package:highlight/languages/kotlin.dart';
import 'package:highlight/languages/swift.dart';
import 'package:highlight/languages/cpp.dart';
import 'package:highlight/languages/cs.dart'; // csharp
import 'package:highlight/languages/go.dart';
import 'package:highlight/languages/rust.dart';
import 'package:highlight/languages/sql.dart';
import 'package:highlight/languages/yaml.dart';
import 'package:highlight/languages/xml.dart';
import 'package:highlight/languages/bash.dart';
import 'package:highlight/languages/shell.dart';
import 'package:highlight/languages/markdown.dart';
import 'package:highlight/languages/css.dart';
import 'package:highlight/languages/php.dart';
import 'package:highlight/languages/ruby.dart';
import 'package:highlight/languages/cmake.dart';
import 'package:highlight/languages/makefile.dart';
import 'package:highlight/languages/nginx.dart';
import 'package:highlight/languages/dockerfile.dart';
import 'package:highlight/languages/gradle.dart';
import 'package:highlight/languages/groovy.dart';
import 'package:highlight/languages/ini.dart';
import 'package:highlight/languages/less.dart';
import 'package:highlight/languages/lua.dart';
import 'package:highlight/languages/objectivec.dart';
import 'package:highlight/languages/perl.dart';
import 'package:highlight/languages/plaintext.dart';
import 'package:highlight/languages/powershell.dart';
import 'package:highlight/languages/r.dart';
import 'package:highlight/languages/scala.dart';
import 'package:highlight/languages/scss.dart';
import 'package:highlight/languages/vbnet.dart';
import 'package:highlight/languages/vim.dart';

final Map<String, Mode> allLanguages = {
  'dart': dart,
  'json': json,
  'python': python,
  'py': python,
  'javascript': javascript,
  'js': javascript,
  'typescript': typescript,
  'ts': typescript,
  'java': java,
  'kotlin': kotlin,
  'swift': swift,
  'cpp': cpp,
  'c++': cpp,
  'c': cpp, // cpp mode often handles c too or I should import c.dart if available
  'cs': cs,
  'csharp': cs,
  'c#': cs,
  'go': go,
  'rust': rust,
  'sql': sql,
  'yaml': yaml,
  'yml': yaml,
  'xml': xml,
  'bash': bash,
  'sh': bash,
  'shell': shell,
  'markdown': markdown,
  'md': markdown,
  'css': css,
  'php': php,
  'ruby': ruby,
  'rb': ruby,
  'cmake': cmake,
  'makefile': makefile,
  'nginx': nginx,
  'dockerfile': dockerfile,
  'docker': dockerfile,
  'gradle': gradle,
  'groovy': groovy,
  'ini': ini,
  'less': less,
  'lua': lua,
  'objectivec': objectivec,
  'perl': perl,
  'plaintext': plaintext,
  'txt': plaintext,
  'powershell': powershell,
  'ps1': powershell,
  'r': r,
  'scala': scala,
  'scss': scss,
  'vbnet': vbnet,
  'vim': vim,
};
