"""cowork_crypto — the byte-identical Python twin of the Dart CoWork frame crypto.

Wire-compatible with ``lib/services/cowork/cowork_frame*.dart`` in chuk_chat.
See ``fixtures/test_vectors.json`` and the README for the cross-language
byte-compat contract.
"""

from .approved_devices import ApprovedDevices
from .channel_key import (
    CHANNEL_KEY_INFO,
    CHANNEL_KEY_LENGTH,
    derive_channel_key,
    generate_x25519_keypair,
)
from .device_keys import (
    FINGERPRINT_BYTES,
    PUBLIC_KEY_LENGTH,
    SEED_LENGTH,
    DeviceIdentity,
    fingerprint,
    public_key_from_base64,
)
from .frame import (
    FRAME_VERSION,
    MAC_LENGTH,
    NONCE_LENGTH,
    SIGNATURE_LENGTH,
    CoworkFrame,
    CoworkFrameRejected,
    CoworkFrameRejection,
    build_header_bytes,
    build_signed_bytes,
)
from .pairing import (
    COMMIT_LABEL,
    CONFIRM_C_LABEL,
    CONFIRM_D_LABEL,
    DEFAULT_EXPIRY_MS,
    DEFAULT_SAS_DIGITS,
    DEVICE_C_LABEL,
    DEVICE_D_LABEL,
    DEVICE_PROOF_LABEL,
    SAS_LABEL,
    Pairing,
    PairingError,
    PairingRejection,
    PairingRole,
    PairingState,
    commitment,
    derive_confirm_mac,
    derive_sas,
    transcript,
)
from .reconnect import (
    RECONNECT_I_LABEL,
    RECONNECT_J_LABEL,
    RECONNECT_NONCE_LENGTH,
    ReconnectError,
    ReconnectHandshake,
    ReconnectRejection,
    ReconnectRole,
    ReconnectState,
    reconnect_signed_bytes,
    reconnect_transcript,
)
from .replay_guard import DEFAULT_WINDOW_MS, ReplayGuard
from .sealer import CoworkFrameOpener, CoworkFrameSealer, open, seal

__all__ = [
    "ApprovedDevices",
    "CHANNEL_KEY_INFO",
    "CHANNEL_KEY_LENGTH",
    "COMMIT_LABEL",
    "CONFIRM_C_LABEL",
    "CONFIRM_D_LABEL",
    "CoworkFrame",
    "CoworkFrameOpener",
    "CoworkFrameRejected",
    "CoworkFrameRejection",
    "CoworkFrameSealer",
    "DEFAULT_EXPIRY_MS",
    "DEFAULT_SAS_DIGITS",
    "DEFAULT_WINDOW_MS",
    "DEVICE_C_LABEL",
    "DEVICE_D_LABEL",
    "DEVICE_PROOF_LABEL",
    "DeviceIdentity",
    "FINGERPRINT_BYTES",
    "FRAME_VERSION",
    "MAC_LENGTH",
    "NONCE_LENGTH",
    "PUBLIC_KEY_LENGTH",
    "Pairing",
    "PairingError",
    "PairingRejection",
    "PairingRole",
    "PairingState",
    "RECONNECT_I_LABEL",
    "RECONNECT_J_LABEL",
    "RECONNECT_NONCE_LENGTH",
    "ReconnectError",
    "ReconnectHandshake",
    "ReconnectRejection",
    "ReconnectRole",
    "ReconnectState",
    "ReplayGuard",
    "SAS_LABEL",
    "SEED_LENGTH",
    "SIGNATURE_LENGTH",
    "build_header_bytes",
    "build_signed_bytes",
    "commitment",
    "derive_channel_key",
    "derive_confirm_mac",
    "derive_sas",
    "fingerprint",
    "generate_x25519_keypair",
    "open",
    "public_key_from_base64",
    "reconnect_signed_bytes",
    "reconnect_transcript",
    "seal",
    "transcript",
]
