"""CoWork Python agent runtime — the loop, tools, state, and model client (§7)."""

from __future__ import annotations

from .backend import (
    DEFAULT_BASE_URL,
    DEFAULT_MODEL_ID,
    BackendModelClient,
    BackendModelError,
    ResolvedModel,
    SupabaseAuthError,
    SupabaseSession,
    fetch_models_info,
    login,
    resolve_model,
)
from .context import (
    DEFAULT_CONTEXT_LENGTH,
    DEFAULT_RESERVED_OUTPUT,
    SUMMARY_PREFIX,
    SUMMARY_TEMPLATE,
    AuxSummarizer,
    CompressionStats,
    ContextLadder,
    LadderConfig,
    Summarizer,
    build_summary_prompt,
    estimate_message_tokens,
    estimate_messages_tokens,
    estimate_tokens,
    expand_back_references,
    prompt_tokens_from_usage,
    redact_message,
    redact_secrets,
    render_transcript,
)
from .environment import Environment, LocalEnvironment, ProcessResult
from .loop import (
    AgentLoop,
    IterationBudget,
    KillSwitch,
    LoopResult,
    StopReason,
)
from .memory import (
    MAX_ENTRY_CHARS,
    MAX_FILE_CHARS,
    MemoryStore,
    MemoryToolError,
    register_memory_tool,
)
from .model import (
    ModelClient,
    ModelResponse,
    MockModelClient,
    OpenAICompatModelClient,
    ToolCall,
    extract_tool_calls,
    parse_openai_response,
    response_from_content,
)
from .prompt import (
    BASE_INSTRUCTIONS,
    TOOL_PROTOCOL,
    build_system_prompt,
    render_tool_docs,
)
from .registry import ToolRegistry, ToolSpec
from .runtime import build_runtime
from .search import (
    register_search_tool,
    sanitize_match,
    search_messages,
    segment_cjk,
)
from .skills import (
    MAX_DESCRIPTION_CHARS,
    Skill,
    SkillError,
    SkillLibrary,
    load_skills,
    parse_skill,
    register_skill_tool,
)
from .state import Message, StateStore
from .think_scrubber import ThinkScrubber, scrub_history, scrub_text
from .tools import register_builtin_tools, register_file_tools, register_run_command
from .web_fetch import (
    FETCH_CAP,
    UrlRejected,
    html_to_markdown,
    is_blocked_address,
    make_web_fetch_handler,
    register_web_fetch,
    validate_url,
)
from .web_search import (
    TokenSession,
    make_web_search_handler,
    register_web_search,
)
from .workspace_git import (
    ARG_VALUE_CAP,
    DEFAULT_MAX_BLOB_BYTES,
    JOURNAL_PATH,
    RESULT_CAP,
    CommitInfo,
    GitWorkspace,
    redact_args,
    summarize_result,
)
from .workspace_tools import (
    JournalingRegistry,
    register_workspace_tools,
)

__all__ = [
    "ARG_VALUE_CAP",
    "BASE_INSTRUCTIONS",
    "DEFAULT_BASE_URL",
    "DEFAULT_CONTEXT_LENGTH",
    "DEFAULT_MAX_BLOB_BYTES",
    "DEFAULT_MODEL_ID",
    "DEFAULT_RESERVED_OUTPUT",
    "FETCH_CAP",
    "JOURNAL_PATH",
    "MAX_DESCRIPTION_CHARS",
    "MAX_ENTRY_CHARS",
    "MAX_FILE_CHARS",
    "RESULT_CAP",
    "SUMMARY_PREFIX",
    "SUMMARY_TEMPLATE",
    "TOOL_PROTOCOL",
    "AgentLoop",
    "AuxSummarizer",
    "BackendModelClient",
    "BackendModelError",
    "CommitInfo",
    "CompressionStats",
    "ContextLadder",
    "Environment",
    "GitWorkspace",
    "IterationBudget",
    "JournalingRegistry",
    "KillSwitch",
    "LadderConfig",
    "LocalEnvironment",
    "LoopResult",
    "MemoryStore",
    "MemoryToolError",
    "Message",
    "MockModelClient",
    "ModelClient",
    "ModelResponse",
    "OpenAICompatModelClient",
    "ProcessResult",
    "ResolvedModel",
    "Skill",
    "SkillError",
    "SkillLibrary",
    "StateStore",
    "StopReason",
    "Summarizer",
    "SupabaseAuthError",
    "SupabaseSession",
    "ThinkScrubber",
    "TokenSession",
    "ToolCall",
    "ToolRegistry",
    "ToolSpec",
    "UrlRejected",
    "build_runtime",
    "build_summary_prompt",
    "build_system_prompt",
    "estimate_message_tokens",
    "estimate_messages_tokens",
    "estimate_tokens",
    "expand_back_references",
    "extract_tool_calls",
    "fetch_models_info",
    "html_to_markdown",
    "is_blocked_address",
    "load_skills",
    "login",
    "make_web_fetch_handler",
    "make_web_search_handler",
    "parse_openai_response",
    "parse_skill",
    "prompt_tokens_from_usage",
    "redact_args",
    "redact_message",
    "redact_secrets",
    "register_builtin_tools",
    "register_file_tools",
    "register_memory_tool",
    "register_run_command",
    "register_search_tool",
    "register_skill_tool",
    "register_web_fetch",
    "register_web_search",
    "register_workspace_tools",
    "render_tool_docs",
    "render_transcript",
    "resolve_model",
    "response_from_content",
    "sanitize_match",
    "scrub_history",
    "scrub_text",
    "search_messages",
    "segment_cjk",
    "summarize_result",
    "validate_url",
]
