"""CoWork Python agent runtime — the loop, tools, state, and model client (§7)."""

from __future__ import annotations

from .backend import (
    DEFAULT_BASE_URL,
    DEFAULT_MODEL_ID,
    BackendModelClient,
    BackendModelError,
    ResolvedModel,
    SupabaseAuthError,
    SupabaseSession,
    fetch_models_info,
    login,
    resolve_model,
)
from .context import (
    DEFAULT_CONTEXT_LENGTH,
    DEFAULT_RESERVED_OUTPUT,
    SUMMARY_PREFIX,
    SUMMARY_TEMPLATE,
    AuxSummarizer,
    CompressionStats,
    ContextLadder,
    LadderConfig,
    Summarizer,
    build_summary_prompt,
    estimate_message_tokens,
    estimate_messages_tokens,
    estimate_tokens,
    expand_back_references,
    prompt_tokens_from_usage,
    redact_message,
    redact_secrets,
    render_transcript,
)
from .environment import Environment, LocalEnvironment, ProcessResult
from .loop import (
    AgentLoop,
    IterationBudget,
    KillSwitch,
    LoopResult,
    StopReason,
)
from .model import (
    ModelClient,
    ModelResponse,
    MockModelClient,
    OpenAICompatModelClient,
    ToolCall,
    extract_tool_calls,
    parse_openai_response,
    response_from_content,
)
from .prompt import (
    BASE_INSTRUCTIONS,
    TOOL_PROTOCOL,
    build_system_prompt,
    render_tool_docs,
)
from .registry import ToolRegistry, ToolSpec
from .runtime import build_runtime
from .state import Message, StateStore
from .think_scrubber import ThinkScrubber, scrub_history, scrub_text
from .tools import register_builtin_tools, register_file_tools, register_run_command

__all__ = [
    "BASE_INSTRUCTIONS",
    "SUMMARY_PREFIX",
    "SUMMARY_TEMPLATE",
    "TOOL_PROTOCOL",
    "AgentLoop",
    "AuxSummarizer",
    "BackendModelClient",
    "BackendModelError",
    "CompressionStats",
    "ContextLadder",
    "DEFAULT_BASE_URL",
    "DEFAULT_CONTEXT_LENGTH",
    "DEFAULT_MODEL_ID",
    "DEFAULT_RESERVED_OUTPUT",
    "Environment",
    "IterationBudget",
    "KillSwitch",
    "LadderConfig",
    "LocalEnvironment",
    "LoopResult",
    "Message",
    "ModelClient",
    "ModelResponse",
    "MockModelClient",
    "OpenAICompatModelClient",
    "ProcessResult",
    "ResolvedModel",
    "StateStore",
    "StopReason",
    "Summarizer",
    "SupabaseAuthError",
    "SupabaseSession",
    "ThinkScrubber",
    "ToolCall",
    "ToolRegistry",
    "ToolSpec",
    "build_runtime",
    "build_summary_prompt",
    "build_system_prompt",
    "estimate_message_tokens",
    "estimate_messages_tokens",
    "estimate_tokens",
    "expand_back_references",
    "extract_tool_calls",
    "fetch_models_info",
    "login",
    "parse_openai_response",
    "prompt_tokens_from_usage",
    "redact_message",
    "redact_secrets",
    "register_builtin_tools",
    "register_file_tools",
    "register_run_command",
    "render_tool_docs",
    "render_transcript",
    "resolve_model",
    "response_from_content",
    "scrub_history",
    "scrub_text",
]
